openapi: 3.0.0
info:
  title: Simple dashboard for PostgreSQL
  version: 0.0.1
servers:
  - url: http://localhost:8001/api
tags:
  - name: cluster
    description: Everything related to Postgres cluster data
paths:
  /cluster/status:
    get:
      tags:
        - cluster
      summary: Get server current status
      operationId: GetStatus
      responses:
        200:
          description: Server current status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponse"
              examples:
                success:
                  summary: Status received successfully
                  value:
                    postgres_connection: active
                connection lost:
                  summary: Status with lost connection
                  value:
                    postgres_connection: lost
        400:
          description: Request server status failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponseError"
  /cluster/connect:
    post:
      tags:
        - cluster
      summary: Connect to Postgres cluster
      description: Connect to Postgres cluster
      operationId: ClusterConnect
      requestBody:
        required: true
        description: Request's data payload
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClusterConnectData"
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponse"
        422:
          description: Request data invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestValidationError"
        400:
          description: Connection attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    RequestValidationError:
      type: object
      properties:
        message:
          type: string
          example: some body fields are invalid
      required:
        - message
    BadRequestError:
      type: object
      properties:
        error:
          type: string
          example: error details
      required:
        - error
    ConnectionStatus:
      type: string
      enum: [active, lost, connecting, error]
      x-enum-varnames:
        - PgConnectionStatusActive,
        - PgConnectionStatusLost,
        - PgConnectionStatusConnecting,
        - PgConnectionStatusError,
      description: PostgreSQL connection state
    GetStatusResponse:
      type: object
      required:
        - postgres_connection
      properties:
        postgres_connection:
          $ref: "#/components/schemas/ConnectionStatus"
          example: active
          description: Represents connection state between dashboard and postgres
    GetStatusResponseError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: failed to get cluster status
    ClusterConnectData: # internal/scopes/cluster/entities/entities.go
      x-go-type: clusterEntities.AuthData
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: clusterEntities
      x-go-type-name: clusterEntities.AuthData
      type: object
      required:
        - host
        - port
        - user
        - password
        - database
        - sslmode
      properties:
        host:
          type: string
          example: 127.0.0.1
        port:
          type: integer
          example: 5432
        user:
          type: string
          example: postgres
        password:
          type: string
          example: postgres
        database:
          type: string
          example: postgres
        sslmode:
          type: string
          example: ""
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
