openapi: 3.0.0
info:
  title: Simple dashboard for PostgreSQL
  version: 0.0.1
servers:
  - url: http://localhost:8001/api
tags:
  - name: cluster
    description: Everything related to Postgres cluster data
paths:
  /cluster/status:
    get:
      tags:
        - cluster
      summary: Get server current status
      operationId: GetStatus
      responses:
        200:
          description: Server current status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponse"
              examples:
                success:
                  summary: Status received successfully
                  value:
                    postgres_connection: active
                connection lost:
                  summary: Status with lost connection
                  value:
                    postgres_connection: lost
        400:
          description: Request server status failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponseError"
components:
  schemas:
    ConnectionStatus:
      type: string
      enum: [active, lost, connecting, error]
      x-enum-varnames:
        - PgConnectionStatusActive,
        - PgConnectionStatusLost,
        - PgConnectionStatusConnecting,
        - PgConnectionStatusError,
      description: PostgreSQL connection state
    GetStatusResponse:
      type: object
      required:
        - postgres_connection
      properties:
        postgres_connection:
          $ref: "#/components/schemas/ConnectionStatus"
          example: active
          description: Represents connection state between dashboard and postgres
    GetStatusResponseError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: failed to get cluster status
