openapi: 3.0.0
info:
  title: Simple dashboard for PostgreSQL
  version: 0.0.1
  description: Collection of all available REST handlers
servers:
  - url: http://localhost:8001/api
tags:
  - name: cluster
    description: Everything related to Postgres cluster data
paths:
  /cluster/status:
    get:
      tags:
        - cluster
      summary: Get server current status
      operationId: GetStatus
      responses:
        "200":
          description: Server current status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponse"
              examples:
                success:
                  summary: Status received successfully
                  value:
                    postgres_connection: connected
                connection lost:
                  summary: Status with lost connection
                  value:
                    postgres_connection: disconnected
        "400":
          description: Request server status failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/connect:
    post:
      tags:
        - cluster
      summary: Connect to Postgres cluster
      description: Connect to Postgres cluster
      operationId: ClusterConnect
      requestBody:
        required: true
        description: Request's data payload
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClusterConnectData"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponse"
        "422":
          description: Request data invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestValidationError"
        "400":
          description: Connection attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/disconnect:
    post:
      tags:
        - cluster
      summary: Disconnect from Postgres cluster
      description: Disconnect from Postgres cluster
      operationId: ClusterDisconnect
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponse"
        "400":
          description: Disonnection attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/version:
    get:
      tags:
        - cluster
      summary: Get detailed Postgres version info
      description: Get detailed Postgres version info
      operationId: PostgresVersion
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPostgresVersionResponse"
        "400":
          description: Attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/uptime:
    get:
      tags:
        - cluster
      summary: Get Postgres uptime info
      description: Get Postgres uptime info
      operationId: PostgresUptime
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPostgresUptimeResponse"
        "400":
          description: Attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/postmaster-settings:
    get:
      tags:
        - cluster
      summary: Get global cluster settings
      description: Returns some settings from pg_settings in the "postmaster" context.
      operationId: PostmasterSettings
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/GetPostgresPostmasterSettings"
                example:
                  configFile:
                    name: config_file
                    value: /Library/PostgreSQL/16/data/postgresql.conf
                    unit: ""
                    description: Sets the server's main configuration file
                  dataDirectory:
                    name: data_directory
                    value: /Library/PostgreSQL/16/data
                    unit: ""
                    description: Sets the server's data directory.
                  sharedBuffers:
                    name: shared_buffers
                    value: 256 MB
                    unit: 8kB
                    description: Sets the number of shared memory buffers used by the server.
                  walBuffers:
                    name: wal_buffers
                    value: 8 MB
                    unit: 8kB
                    description: Sets the number of disk-page buffers in shared memory for WAL.
                  maxConnections:
                    name: max_connections
                    value: "100"
                    unit: ""
                    description: Sets the maximum number of concurrent connections.
                  hbaFile:
                    name: hba_file
                    value: /Library/PostgreSQL/16/data/pg_hba.conf
                    unit: ""
                    description: Sets the server's "hba" configuration file.
                  walLevel:
                    name: wal_level
                    value: replica
                    unit: ""
                    description: Sets the level of information written to the WAL.

        "400":
          description: Attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
components:
  schemas:
    ErrorBase:
      type: object
      description: Error part that should be present in all errors
      required:
        - message
      properties:
        message:
          type: string
          example: something went wrong
    RequestValidationError:
      allOf:
        - $ref: "#/components/schemas/ErrorBase"
        - type: object
          properties:
            reason:
              type: string
              example: the body fields are invalid
          required:
            - reason
    ConnectionStatus:
      type: string
      description: Represents connection state between dashboard and postgres
      example: connected
      enum: [connecting, connected, disconnected, error]
      x-enum-varnames:
        - PgConnectionStatusConnecting,
        - PgConnectionStatusConnected,
        - PgConnectionStatusDisconnected,
        - PgConnectionStatusError,
    PostgresSetting:
      type: object
      description: Represents some columns from "pg_catalog.pg_settings"
      x-go-type: clusterEntities.Setting
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: Setting
      x-go-type-name: clusterEntities.Setting
      required:
        - name
        - value
        - unit
        - description
      properties:
        name:
          type: string
          example: shared_buffers
        value:
          type: string
          example: "32768"
        unit:
          type: string
          example: 8kB
        description:
          type: string
          example: Sets the number of...
    GetStatusResponse:
      type: object
      required:
        - postgres_connection
      properties:
        postgres_connection:
          $ref: "#/components/schemas/ConnectionStatus"
    ClusterConnectData: # internal/scopes/cluster/entities/entities.go
      x-go-type: clusterEntities.AuthData
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: clusterEntities
      x-go-type-name: clusterEntities.AuthData
      type: object
      required:
        - host
        - port
        - user
        - password
        - sslmode
      properties:
        host:
          type: string
          example: 127.0.0.1
        port:
          type: integer
          example: 5432
        user:
          type: string
          example: postgres
        password:
          type: string
          example: postgres
        database:
          type: string
          example: postgres
        sslmode:
          type: string
          example: ""
    GetPostgresVersionResponse:
      x-go-type: clusterEntities.PostgresVersion
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: clusterEntities
      x-go-type-name: clusterEntities.PostgresVersion
      type: object
      required:
        - version
        - compiler
        - bitDepth
      properties:
        version:
          type: string
          example: PostgreSQL 15.3 on x86_64-pc-linux-gnu
        compiler:
          type: string
          example: compiled by gcc (Ubuntu 11.3.0) 11.3.0
        bitDepth:
          type: string
          example: 64-bit
    GetPostgresUptimeResponse:
      x-go-type: clusterEntities.PostgresUptime
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: clusterEntities
      x-go-type-name: clusterEntities.PostgresUptime
      type: object
      description: Returns an ISO-8601 string with timezone
      required:
        - startedAt
      properties:
        startedAt:
          type: string
          example: 2025-12-05 13:45:06.746931+02
    GetPostgresPostmasterSettings:
      x-go-type: clusterEntities.PostmasterSettings
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: PostmasterSettings
      x-go-type-name: clusterEntities.PostmasterSettings
      type: object
      description: Represents some settings from pg_settings in the "postmaster" context.
      required:
        - configFile
        - dataDirectory
        - sharedBuffers
        - walBuffers
        - maxConnections
        - hbaFile
        - walLevel
      properties:
        configFile:
          $ref: "#/components/schemas/PostgresSetting"
        dataDirectory:
          $ref: "#/components/schemas/PostgresSetting"
        sharedBuffers:
          $ref: "#/components/schemas/PostgresSetting"
        walBuffers:
          $ref: "#/components/schemas/PostgresSetting"
        maxConnections:
          $ref: "#/components/schemas/PostgresSetting"
        hbaFile:
          $ref: "#/components/schemas/PostgresSetting"
        walLevel:
          $ref: "#/components/schemas/PostgresSetting"
