// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: database.proto

package codec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostgresDbOverviewStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Tables        int64                  `protobuf:"varint,4,opt,name=tables,proto3" json:"tables,omitempty"`
	Indexes       int64                  `protobuf:"varint,5,opt,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresDbOverviewStats) Reset() {
	*x = PostgresDbOverviewStats{}
	mi := &file_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresDbOverviewStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresDbOverviewStats) ProtoMessage() {}

func (x *PostgresDbOverviewStats) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresDbOverviewStats.ProtoReflect.Descriptor instead.
func (*PostgresDbOverviewStats) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{0}
}

func (x *PostgresDbOverviewStats) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostgresDbOverviewStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostgresDbOverviewStats) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PostgresDbOverviewStats) GetTables() int64 {
	if x != nil {
		return x.Tables
	}
	return 0
}

func (x *PostgresDbOverviewStats) GetIndexes() int64 {
	if x != nil {
		return x.Indexes
	}
	return 0
}

type StoredOverviewStats struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Current       *PostgresDbOverviewStats `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	Previous      *PostgresDbOverviewStats `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"`
	ChangedAt     *timestamppb.Timestamp   `protobuf:"bytes,3,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredOverviewStats) Reset() {
	*x = StoredOverviewStats{}
	mi := &file_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredOverviewStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredOverviewStats) ProtoMessage() {}

func (x *StoredOverviewStats) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredOverviewStats.ProtoReflect.Descriptor instead.
func (*StoredOverviewStats) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{1}
}

func (x *StoredOverviewStats) GetCurrent() *PostgresDbOverviewStats {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *StoredOverviewStats) GetPrevious() *PostgresDbOverviewStats {
	if x != nil {
		return x.Previous
	}
	return nil
}

func (x *StoredOverviewStats) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

var File_database_proto protoreflect.FileDescriptor

const file_database_proto_rawDesc = "" +
	"\n" +
	"\x0edatabase.proto\x12\x05codec\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\x17PostgresDbOverviewStats\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06tables\x18\x04 \x01(\x03R\x06tables\x12\x18\n" +
	"\aindexes\x18\x05 \x01(\x03R\aindexes\"\xc6\x01\n" +
	"\x13StoredOverviewStats\x128\n" +
	"\acurrent\x18\x01 \x01(\v2\x1e.codec.PostgresDbOverviewStatsR\acurrent\x12:\n" +
	"\bprevious\x18\x02 \x01(\v2\x1e.codec.PostgresDbOverviewStatsR\bprevious\x129\n" +
	"\n" +
	"changed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAtB\x0fZ\rstorage/codecb\x06proto3"

var (
	file_database_proto_rawDescOnce sync.Once
	file_database_proto_rawDescData []byte
)

func file_database_proto_rawDescGZIP() []byte {
	file_database_proto_rawDescOnce.Do(func() {
		file_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)))
	})
	return file_database_proto_rawDescData
}

var file_database_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_database_proto_goTypes = []any{
	(*PostgresDbOverviewStats)(nil), // 0: codec.PostgresDbOverviewStats
	(*StoredOverviewStats)(nil),     // 1: codec.StoredOverviewStats
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
}
var file_database_proto_depIdxs = []int32{
	0, // 0: codec.StoredOverviewStats.current:type_name -> codec.PostgresDbOverviewStats
	0, // 1: codec.StoredOverviewStats.previous:type_name -> codec.PostgresDbOverviewStats
	2, // 2: codec.StoredOverviewStats.changed_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_database_proto_init() }
func file_database_proto_init() {
	if File_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_database_proto_goTypes,
		DependencyIndexes: file_database_proto_depIdxs,
		MessageInfos:      file_database_proto_msgTypes,
	}.Build()
	File_database_proto = out.File
	file_database_proto_goTypes = nil
	file_database_proto_depIdxs = nil
}
