/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUiRouteImport } from './routes/_authenticated/ui'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedDatabaseDatabaseIdRouteImport } from './routes/_authenticated/database/$databaseId'
import { Route as AuthenticatedDatabaseDatabaseIdIndexRouteImport } from './routes/_authenticated/database/$databaseId.index'
import { Route as AuthenticatedDatabaseDatabaseIdTablesRouteImport } from './routes/_authenticated/database/$databaseId.tables'
import { Route as AuthenticatedDatabaseDatabaseIdIndexesRouteImport } from './routes/_authenticated/database/$databaseId.indexes'

const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUiRoute = AuthenticatedUiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatabaseDatabaseIdRoute =
  AuthenticatedDatabaseDatabaseIdRouteImport.update({
    id: '/database/$databaseId',
    path: '/database/$databaseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatabaseDatabaseIdIndexRoute =
  AuthenticatedDatabaseDatabaseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDatabaseDatabaseIdRoute,
  } as any)
const AuthenticatedDatabaseDatabaseIdTablesRoute =
  AuthenticatedDatabaseDatabaseIdTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () => AuthenticatedDatabaseDatabaseIdRoute,
  } as any)
const AuthenticatedDatabaseDatabaseIdIndexesRoute =
  AuthenticatedDatabaseDatabaseIdIndexesRouteImport.update({
    id: '/indexes',
    path: '/indexes',
    getParentRoute: () => AuthenticatedDatabaseDatabaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/connect': typeof ConnectRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ui': typeof AuthenticatedUiRoute
  '/': typeof AuthenticatedIndexRoute
  '/database/$databaseId': typeof AuthenticatedDatabaseDatabaseIdRouteWithChildren
  '/database/$databaseId/indexes': typeof AuthenticatedDatabaseDatabaseIdIndexesRoute
  '/database/$databaseId/tables': typeof AuthenticatedDatabaseDatabaseIdTablesRoute
  '/database/$databaseId/': typeof AuthenticatedDatabaseDatabaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/connect': typeof ConnectRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ui': typeof AuthenticatedUiRoute
  '/': typeof AuthenticatedIndexRoute
  '/database/$databaseId/indexes': typeof AuthenticatedDatabaseDatabaseIdIndexesRoute
  '/database/$databaseId/tables': typeof AuthenticatedDatabaseDatabaseIdTablesRoute
  '/database/$databaseId': typeof AuthenticatedDatabaseDatabaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/connect': typeof ConnectRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ui': typeof AuthenticatedUiRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/database/$databaseId': typeof AuthenticatedDatabaseDatabaseIdRouteWithChildren
  '/_authenticated/database/$databaseId/indexes': typeof AuthenticatedDatabaseDatabaseIdIndexesRoute
  '/_authenticated/database/$databaseId/tables': typeof AuthenticatedDatabaseDatabaseIdTablesRoute
  '/_authenticated/database/$databaseId/': typeof AuthenticatedDatabaseDatabaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/connect'
    | '/apps'
    | '/dashboard'
    | '/ui'
    | '/'
    | '/database/$databaseId'
    | '/database/$databaseId/indexes'
    | '/database/$databaseId/tables'
    | '/database/$databaseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect'
    | '/apps'
    | '/dashboard'
    | '/ui'
    | '/'
    | '/database/$databaseId/indexes'
    | '/database/$databaseId/tables'
    | '/database/$databaseId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/connect'
    | '/_authenticated/apps'
    | '/_authenticated/dashboard'
    | '/_authenticated/ui'
    | '/_authenticated/'
    | '/_authenticated/database/$databaseId'
    | '/_authenticated/database/$databaseId/indexes'
    | '/_authenticated/database/$databaseId/tables'
    | '/_authenticated/database/$databaseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ConnectRoute: typeof ConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui': {
      id: '/_authenticated/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof AuthenticatedUiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/database/$databaseId': {
      id: '/_authenticated/database/$databaseId'
      path: '/database/$databaseId'
      fullPath: '/database/$databaseId'
      preLoaderRoute: typeof AuthenticatedDatabaseDatabaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/database/$databaseId/': {
      id: '/_authenticated/database/$databaseId/'
      path: '/'
      fullPath: '/database/$databaseId/'
      preLoaderRoute: typeof AuthenticatedDatabaseDatabaseIdIndexRouteImport
      parentRoute: typeof AuthenticatedDatabaseDatabaseIdRoute
    }
    '/_authenticated/database/$databaseId/tables': {
      id: '/_authenticated/database/$databaseId/tables'
      path: '/tables'
      fullPath: '/database/$databaseId/tables'
      preLoaderRoute: typeof AuthenticatedDatabaseDatabaseIdTablesRouteImport
      parentRoute: typeof AuthenticatedDatabaseDatabaseIdRoute
    }
    '/_authenticated/database/$databaseId/indexes': {
      id: '/_authenticated/database/$databaseId/indexes'
      path: '/indexes'
      fullPath: '/database/$databaseId/indexes'
      preLoaderRoute: typeof AuthenticatedDatabaseDatabaseIdIndexesRouteImport
      parentRoute: typeof AuthenticatedDatabaseDatabaseIdRoute
    }
  }
}

interface AuthenticatedDatabaseDatabaseIdRouteChildren {
  AuthenticatedDatabaseDatabaseIdIndexesRoute: typeof AuthenticatedDatabaseDatabaseIdIndexesRoute
  AuthenticatedDatabaseDatabaseIdTablesRoute: typeof AuthenticatedDatabaseDatabaseIdTablesRoute
  AuthenticatedDatabaseDatabaseIdIndexRoute: typeof AuthenticatedDatabaseDatabaseIdIndexRoute
}

const AuthenticatedDatabaseDatabaseIdRouteChildren: AuthenticatedDatabaseDatabaseIdRouteChildren =
  {
    AuthenticatedDatabaseDatabaseIdIndexesRoute:
      AuthenticatedDatabaseDatabaseIdIndexesRoute,
    AuthenticatedDatabaseDatabaseIdTablesRoute:
      AuthenticatedDatabaseDatabaseIdTablesRoute,
    AuthenticatedDatabaseDatabaseIdIndexRoute:
      AuthenticatedDatabaseDatabaseIdIndexRoute,
  }

const AuthenticatedDatabaseDatabaseIdRouteWithChildren =
  AuthenticatedDatabaseDatabaseIdRoute._addFileChildren(
    AuthenticatedDatabaseDatabaseIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedUiRoute: typeof AuthenticatedUiRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDatabaseDatabaseIdRoute: typeof AuthenticatedDatabaseDatabaseIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppsRoute: AuthenticatedAppsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedUiRoute: AuthenticatedUiRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDatabaseDatabaseIdRoute:
    AuthenticatedDatabaseDatabaseIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ConnectRoute: ConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
